spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: igpark0523@gmail.com
    password: ouzalivhsyxqyeo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000  # 3 * 60 * 1000 == 3분