-- 전체 시퀀스와 테이블 제거
DROP SEQUENCE author_idx;
DROP SEQUENCE publisher_idx;
DROP SEQUENCE book_idx;
DROP SEQUENCE announce_idx;
DROP SEQUENCE inquiry_idx;
DROP SEQUENCE response_idx;
DROP SEQUENCE suspend_idx;
DROP SEQUENCE rents_idx;
DROP SEQUENCE wishlist_idx;
DROP SEQUENCE reservation_idx;
DROP SEQUENCE interest_idx;

DROP INDEX idx_rents_user_id;
DROP INDEX idx_rents_book_id;
DROP INDEX idx_interest_user_id;
DROP INDEX idx_interest_book_id;

DROP TABLE user_genres CASCADE CONSTRAINTS;
DROP TABLE reservations CASCADE CONSTRAINTS;
DROP TABLE wishlists CASCADE CONSTRAINTS;
DROP TABLE rents CASCADE CONSTRAINTS;
DROP TABLE suspensions CASCADE CONSTRAINTS;
DROP TABLE inquiry_responses CASCADE CONSTRAINTS;
DROP TABLE inquiries CASCADE CONSTRAINTS;
DROP TABLE announcements CASCADE CONSTRAINTS;
DROP TABLE admins CASCADE CONSTRAINTS;
DROP TABLE admin_grants CASCADE CONSTRAINTS;
DROP TABLE books CASCADE CONSTRAINTS;
DROP TABLE genres CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE publishers CASCADE CONSTRAINTS;
DROP TABLE authors CASCADE CONSTRAINTS;
DROP TABLE interested_books CASCADE CONSTRAINTS;
DROP TABLE EMAIL_TOKEN CASCADE CONSTRAINTS;
